### PR TITLE
This is my suggestion for reaching common ground

### PR DESCRIPTION
**Pull request by H0ussam**

### CODE REVIEW

**Comment by bellaj** [comment]
` However, it is not in the interest of the players to be malicious because, in the end, only two cups of water will be available.`
This assumption goes against the problem rules. your solution is equivalent to a random selection of 2 winners.
Why would the loser participants (MAJORITY) accept the results ?

**Comment by H0ussam** [comment]
My solution is not equivalent to a random selection, it is indeed a random selection of  2 winners.
It is all based on the assumption that all the guests/players agreed to play it in order to sort the situation out.
From the argument that you gave me, even in the case of racing to put the cup and get the first winner, why would the other losing participants (N-1) accept the result?

**Comment by H0ussam** [comment]
Indeed that sentence goes against the rules and should be removed or replaced "However, it is not in the interest of the players to be malicious because, as the rules of the game dictate all and any attempt of cheating will result in an elimination, and reset of all trials".
I repeat, it is all based on the assumption that all the guests agreed to play this game because it provides a fair framework.
This way I believe this game is not going against the rules, but if you are not satisfied other routes may be explored, let me know what you think :)

**Comment by Ethereumx** [comment]
Please read the rules and abide by them in your proposition, besides your assumption is baseless.
Keep in mind that we look for creative solutions not easy ones.

**Pull request closed without merging**
